mongo:
  variables:
    backup_file: "backup.archive"
  data: "/data/db"
  backup: "mongodump --gzip --archive={{ mongo.dump_path }}/{{ mongo.backup_file }}"
  restore: "mongorestore --gzip --archive={{ mongo.dump_path }}/{{ mongo.backup_file }}"
